//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_LTW_NhaHang
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QL_NhaHangEntities : DbContext
    {
        public QL_NhaHangEntities()
            : base("name=QL_NhaHangEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tblChiTietHoaDon> tblChiTietHoaDons { get; set; }
        public DbSet<tblHinhAnh> tblHinhAnhs { get; set; }
        public DbSet<tblHoaDon> tblHoaDons { get; set; }
        public DbSet<tblKhachHang> tblKhachHangs { get; set; }
        public DbSet<tblLoaiMon> tblLoaiMons { get; set; }
        public DbSet<tblMonAn> tblMonAns { get; set; }
        public DbSet<tblNCC> tblNCCs { get; set; }
        public DbSet<tblNhanVien> tblNhanViens { get; set; }
        public DbSet<tblTinhTrang> tblTinhTrangs { get; set; }
        public DbSet<tblVaiTro> tblVaiTroes { get; set; }
        public DbSet<tblDatBan> tblDatBans { get; set; }
        public DbSet<tblLichSuDoiDiem> tblLichSuDoiDiems { get; set; }
        public DbSet<tblVoucher> tblVouchers { get; set; }
        public DbSet<tblLienHe> tblLienHes { get; set; }
    }
}
