//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_LTW_NhaHang
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDatBan
    {
        public int MaDatBan { get; set; }
        public string TenKhachHang { get; set; }
        public string Email { get; set; }
        public string DienThoai { get; set; }
        public Nullable<System.DateTime> NgayDat { get; set; }
        public Nullable<int> SoNguoi { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> TrangThai { get; set; }
    }
}
