//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_LTW_NhaHang
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDiaChiGiaoHang
    {
        public int MaDiaChi { get; set; }
        public Nullable<int> MaKH { get; set; }
        public string TenNguoiNhan { get; set; }
        public string SoDienThoai { get; set; }
        public string DiaChiChiTiet { get; set; }
        public Nullable<bool> LaMacDinh { get; set; }
    
        public virtual tblKhachHang tblKhachHang { get; set; }
    }
}
