//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_LTW_NhaHang
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHinhAnh
    {
        public int ID { get; set; }
        public Nullable<int> MaMon { get; set; }
        public string TenHinh { get; set; }
    
        public virtual tblMonAn tblMonAn { get; set; }
    }
}
