//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_LTW_NhaHang
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLienHe
    {
        public int MaLH { get; set; }
        public string TenNguoiGui { get; set; }
        public string Email { get; set; }
        public string SoDienThoai { get; set; }
        public string ChuDe { get; set; }
        public string NoiDung { get; set; }
        public Nullable<System.DateTime> NgayGui { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public Nullable<int> SoSao { get; set; }
        public string HinhAnhBinhLuan { get; set; }
    }
}
