//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_LTW_NhaHang
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLichSuDoiDiem
    {
        public int MaLichSu { get; set; }
        public Nullable<int> MaKH { get; set; }
        public Nullable<int> MaVoucher { get; set; }
        public Nullable<System.DateTime> NgayDoi { get; set; }
        public Nullable<int> DiemDaTru { get; set; }
        public string MaCode { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    
        public virtual tblKhachHang tblKhachHang { get; set; }
        public virtual tblVoucher tblVoucher { get; set; }
    }
}
