//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_LTW_NhaHang
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLoaiMon
    {
        public tblLoaiMon()
        {
            this.tblMonAns = new HashSet<tblMonAn>();
        }
    
        public int MaLoai { get; set; }
        public string TenLoai { get; set; }
        public string MoTa { get; set; }
    
        public virtual ICollection<tblMonAn> tblMonAns { get; set; }
    }
}
