//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_LTW_NhaHang
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMonAn
    {
        public tblMonAn()
        {
            this.tblChiTietHoaDons = new HashSet<tblChiTietHoaDon>();
            this.tblHinhAnhs = new HashSet<tblHinhAnh>();
        }
    
        public int MaMon { get; set; }
        public string TenMon { get; set; }
        public Nullable<decimal> DonGia { get; set; }
        public string MoTa { get; set; }
        public string AnhDaiDien { get; set; }
        public Nullable<int> MaLoai { get; set; }
        public Nullable<int> MaNCC { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    
        public virtual ICollection<tblChiTietHoaDon> tblChiTietHoaDons { get; set; }
        public virtual ICollection<tblHinhAnh> tblHinhAnhs { get; set; }
        public virtual tblLoaiMon tblLoaiMon { get; set; }
        public virtual tblNCC tblNCC { get; set; }
    }
}
