//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_LTW_NhaHang
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVoucher
    {
        public tblVoucher()
        {
            this.tblLichSuDoiDiems = new HashSet<tblLichSuDoiDiem>();
        }
    
        public int MaVoucher { get; set; }
        public string TenVoucher { get; set; }
        public Nullable<decimal> GiaTri { get; set; }
        public Nullable<int> DiemDoi { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<System.DateTime> NgayHetHan { get; set; }
    
        public virtual ICollection<tblLichSuDoiDiem> tblLichSuDoiDiems { get; set; }
    }
}
